#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

export CUSTOMER_AGENT_BUSINESS_VLLM_BASE_URL="${CUSTOMER_AGENT_BUSINESS_VLLM_BASE_URL:-http://127.0.0.1:8104/v1}"
# Backwards-compatible alias used by older routes/configuration.
export CUSTOMER_AGENT_VLLM_BASE_URL="${CUSTOMER_AGENT_VLLM_BASE_URL:-$CUSTOMER_AGENT_BUSINESS_VLLM_BASE_URL}"
export CUSTOMER_AGENT_SHADOW_VLLM_BASE_URL="${CUSTOMER_AGENT_SHADOW_VLLM_BASE_URL:-http://127.0.0.1:8302/v1}"
export CUSTOMER_AGENT_MODEL="${CUSTOMER_AGENT_MODEL:-qwen3-8b}"
export CUSTOMER_AGENT_SHADOW_MODEL="${CUSTOMER_AGENT_SHADOW_MODEL:-qwen35-2b}"
export CUSTOMER_AGENT_ENABLE_RUNTIME_PROBES="${CUSTOMER_AGENT_ENABLE_RUNTIME_PROBES:-true}"
export ACTIVATION_PROBE_BACKEND="${ACTIVATION_PROBE_BACKEND:-probe_bank}"
export PROBE_BANK_BASE_URL="${PROBE_BANK_BASE_URL:-http://127.0.0.1:8302}"
export ACTIVATION_PROBE_VLLM_BASE_URL="${ACTIVATION_PROBE_VLLM_BASE_URL:-$CUSTOMER_AGENT_SHADOW_VLLM_BASE_URL}"
export SAFEGAUGE_TOKENIZER_PATH="${SAFEGAUGE_TOKENIZER_PATH:-$PROJECT_ROOT/.runtime/models/Qwen3-8B}"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-18088}"

echo "Customer Agent API: http://127.0.0.1:$PORT/api/customer-agent"
exec python3 -m uvicorn backend.app:app --host "$HOST" --port "$PORT" "$@"
