export const FINVAULT_METHOD_DETAILS = {
  suffix_probe: {
    title: "SafeGauge (Ours)",
    type: "Suffix Probe",
    summary: "用目标模型对一段风险语义后缀的自然反应作为特征，在不读取隐藏状态的情况下判断当前对话是否已经进入高风险金融请求。",
    input: "累计到当前轮的 System Prompt、用户输入与 Assistant 历史",
    timing: "每轮 Assistant 回复前",
    decision: "后缀 token 的 prefill log-probability → MLP → 固定阈值",
    source: {
      label: "LeakDojo · 开源实现",
      url: "https://github.com/yeasen-z/LeakDojo",
      linkLabel: "源码仓库",
    },
    steps: [
      "把截至当前轮的完整对话交给被测模型。",
      "在 Assistant 位置预填充固定风险后缀，读取后缀各 token 的 log-probability 特征。",
      "将特征输入轻量 MLP；分数达到验证集选出的阈值即判为风险。",
      "逐轮重复检测；攻击出现后任一轮命中，整个 Case 即计为检出。",
    ],
  },
  activation_probe: {
    title: "Activation Probe (Ours)",
    type: "Linear Activation Probe",
    summary: "直接读取目标模型在生成回复前的内部 residual-stream 激活，用一个轻量线性分类器识别高风险金融操作意图。",
    input: "累计到当前轮的完整对话",
    timing: "每轮 Assistant 回复前、最后一个输入 token 处",
    decision: "指定 Transformer 层激活 → 线性 Probe → 固定阈值",
    source: {
      label: "Probing-leak-intents · 开源实现",
      url: "https://github.com/jianshuod/Probing-leak-intents",
      linkLabel: "源码仓库",
    },
    steps: [
      "按真实聊天模板编码截至当前轮的全部上下文。",
      "前向计算目标模型，读取最后一个输入 token 在选定层的 residual-stream 向量。",
      "用验证集选出的单层线性 Probe 和阈值计算风险判定。",
      "逐轮重复；历史 Assistant 回复会进入下一轮上下文，但不会用测试标签重新调阈值。",
    ],
  },
  qwen3_guard: {
    title: "Qwen3Guard",
    type: "生成式安全分类器",
    summary: "使用独立的 Qwen3Guard-Gen-8B 阅读累计对话，对当前轮给出 Safe、Controversial 或 Unsafe 分类。",
    input: "累计到当前轮的对话 Query",
    timing: "每轮 Query 进入 Agent 前",
    decision: "Unsafe 或 Controversial 视为命中",
    source: {
      label: "阿里云 Qwen 团队 · 已开源（Apache-2.0）",
      url: "https://github.com/QwenLM/Qwen3Guard",
      linkLabel: "官方仓库",
    },
    steps: [
      "构造截至当前轮的安全分类消息。",
      "调用 Qwen3Guard-Gen-8B 生成安全标签与类别。",
      "Unsafe 或 Controversial 记为本轮检出。",
      "任一攻击轮命中，Case 计为检出。",
    ],
  },
  llama_prompt_guard: {
    title: "Llama Prompt Guard 2",
    type: "提示攻击分类器",
    summary: "使用独立的 86M 参数 Prompt Guard 模型判断输入是否具有提示注入或越狱特征。",
    input: "当前检测范围内的攻击 Query",
    timing: "Query 进入 Agent 前",
    decision: "风险概率达到 0.5 即命中",
    source: {
      label: "Meta · 开放权重（Llama 4 Community License，需授权访问）",
      url: "https://huggingface.co/meta-llama/Llama-Prompt-Guard-2-86M",
      linkLabel: "官方模型页",
    },
    steps: [
      "将待检测 Query 编码为 Prompt Guard 输入。",
      "由 Llama Prompt Guard 2 86M 输出攻击概率。",
      "概率达到固定阈值 0.5 时标记为风险。",
      "按 Case 汇总命中结果。",
    ],
  },
  xguard: {
    title: "YuFeng-XGuard",
    type: "推理式安全分类器",
    summary: "使用独立的 YuFeng-XGuard-Reason-8B 对累计到当前轮的 Query 做安全推理，并输出风险类别与概率。",
    input: "累计到当前轮的对话 Query",
    timing: "每轮 Query 进入 Agent 前",
    decision: "模型风险分类命中即拦截",
    source: {
      label: "Alibaba-AAIG · 已开源（Apache-2.0）",
      url: "https://huggingface.co/Alibaba-AAIG/YuFeng-XGuard-Reason-8B",
      linkLabel: "官方模型页",
    },
    steps: [
      "构造当前轮及其历史上下文。",
      "调用 XGuard 推理安全类别与风险概率。",
      "将风险类别映射为本轮命中或未命中。",
      "任一攻击轮命中，Case 计为检出。",
    ],
  },
  netease_yidun: {
    title: "网易易盾",
    type: "云端文本内容安全服务",
    summary: "只把 FinVault 的 Attack Query 发送给网易易盾文本检测接口，不上传 System Prompt、Assistant 历史、工具返回或 Agent 输出。",
    input: "Attack Query only",
    timing: "Agent 执行前",
    decision: "嫌疑或不通过视为命中",
    source: {
      label: "网易易盾 · 商业闭源服务",
      url: "https://dun.163.com/",
      linkLabel: "官方网站",
    },
    steps: [
      "从 Case 中单独取出 Attack Query。",
      "调用网易易盾文本检测服务。",
      "将嫌疑或不通过建议映射为风险命中。",
      "按 Attack Case 统计检出率。",
    ],
  },
};
